export * from './cliente.model';
export * from './articulo.model';
export * from './venta.model';
export * from './cobro.model';
export * from './gasto.model';
export * from './documento.model';
export * from './visita.model';
export * from './almacen.model';
export * from './app-config.model';
